filter:
    paths: [library/*]
    excluded_paths: [vendor/*, tests/*, docs/*]

before_commands:
    - "composer install --dev --prefer-source"

tools:
    external_code_coverage:
        timeout: 1800
    php_code_sniffer:
        enabled: true
        command: vendor/bin/phpcs
        config:
            standard: PSR2
        filter:
            paths: ["library"]
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["library"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]
    php_mess_detector:
        enabled: true
        command: vendor/bin/phpmd
        config:
            ruleset: phpmd.xml
        filter:
            paths: ["library"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["library/*"]
    sensiolabs_security_checker: true